<?php

namespace Database\Seeders;

use App\Models\Master\Divisi;
use Illuminate\Database\Seeder;

class DivisiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collections = [
            ['unit_kerja_id' => 364, 'nama_divisi' => 'Divisi Transaksi Pinjaman', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 364, 'nama_divisi' => 'Divisi Legal & Administrasi Pinjaman', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Bisnis Korporasi Non BUMD', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 364, 'nama_divisi' => 'Divisi Data & Dokumen Pinjaman', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 641, 'nama_divisi' => 'Divisi Kebijakan Non Bisnis', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 236, 'nama_divisi' => 'Divisi Sistem Akuntansi', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 351, 'nama_divisi' => 'Divisi Kredit Kepemilikan Rumah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 639, 'nama_divisi' => 'Divisi Kredit Mikro II', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 236, 'nama_divisi' => 'Divisi Keuangan & Pelaporan', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Manajemen Audit', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 642, 'nama_divisi' => 'Divisi Audit Umum', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 388, 'nama_divisi' => 'Kantor Kas Tropodo', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Branchless Banking', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 642, 'nama_divisi' => 'Divisi Audit Teknologi Informasi', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Cash & Trade Operation', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 642, 'nama_divisi' => 'Divisi Audit Investigasi & Anti Fraud', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 636, 'nama_divisi' => 'Divisi Digital Banking', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 636, 'nama_divisi' => 'Divisi Digital Banking Ecosystem', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Pemerintah Provinsi DKI Jakarta', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 637, 'nama_divisi' => 'Divisi Pengadaan TI', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Bisnis Ekosistem BUMD', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 332, 'nama_divisi' => 'Divisi Hubungan Bisnis Korporasi Non BUMD', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 232, 'nama_divisi' => 'Divisi Litigasi', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 355, 'nama_divisi' => 'Divisi Manajemen Kinerja & Project Management Office', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 232, 'nama_divisi' => 'Divisi Hukum Korporasi & Perkreditan', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 640, 'nama_divisi' => 'Divisi Kebijakan Bisnis', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 357, 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Ritel', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 233, 'nama_divisi' => 'Divisi Tata Kelola & APU-PPT', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Operasional Manajemen SDM', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 233, 'nama_divisi' => 'Divisi Review Kepatuhan', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 640, 'nama_divisi' => 'Divisi Kredit Komersial', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 351, 'nama_divisi' => 'Divisi Kredit Multi guna', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Dana & Jasa', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Project Management', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 639, 'nama_divisi' => 'Divisi Kredit Mikro II', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 638, 'nama_divisi' => 'Divisi Kredit Ritel I', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 638, 'nama_divisi' => 'Divisi Kredit Ritel II', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 99, 'nama_divisi' => 'Divisi Risiko Operasional', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 99, 'nama_divisi' => 'Divisi Risiko Kredit', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Customer Care', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 244, 'nama_divisi' => 'Divisi Cash Pooling Center', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 636, 'nama_divisi' => 'Divisi Pengelolaan Aset dan Layanan Umum', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 637, 'nama_divisi' => 'Divisi Pengadaan Non-TI', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 637, 'nama_divisi' => 'Divisi Pengadaan TI', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Bisnis Cabang', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Layanan Cabang', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Pendukung Cabang', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 243, 'nama_divisi' => 'Divisi Jaringan Kantor', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 365, 'nama_divisi' => 'Divisi Pengelolaan Produk & Portofolio', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 365, 'nama_divisi' => 'Divisi Bisnis Dana Ritel & Komunitas', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 365, 'nama_divisi' => 'Divisi Transaction Banking', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 355, 'nama_divisi' => 'Divisi Perencanaan & Pengembangan', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Menengah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 634, 'nama_divisi' => 'Divisi Lelang & Portfolio Management', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 357, 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Menengah & Komersial I', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Learning Center', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Strategi & Kebijakan Manajemen SDM', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 72, 'nama_divisi' => 'Divisi Pengembangan & Budaya', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Pembiayaan Menengah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Pembiayaan Konsumer', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 66, 'nama_divisi' => 'Divisi Pembiayaan Mikro & Ritel', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Development', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Operation', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Governance', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Business Analyst', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 358, 'nama_divisi' => 'Divisi IT Project Management', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 69, 'nama_divisi' => 'Divisi Banking Management dan ALMA', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 69, 'nama_divisi' => 'Divisi Global Market', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 359, 'nama_divisi' => 'Divisi Kesekretariatan', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 359, 'nama_divisi' => 'Divisi Komunikasi Pemasaran', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
            ['unit_kerja_id' => 372, 'nama_divisi' => 'Bidang Pelayanan Nasabah', 'created_at' => now(), 'updated_at' => now()],
        ];

        $chunks = array_chunk($collections, config('app.array_chunks_limit'));
        collect($chunks)->each(function ($data) {
            Divisi::insert($data);
        });
    }
}
