<?php

namespace Database\Seeders;

use App\Models\Master\KabupatenKota;
use Illuminate\Database\Seeder;

class KabupatenKotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collections = [
            ['nama' => 'Kota Jakarta Barat', 'id_provinsi' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Jakarta Pusat', 'id_provinsi' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Jakarta Selatan', 'id_provinsi' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Jakarta Timur', 'id_provinsi' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Jakarta Utara', 'id_provinsi' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Seribu', 'id_provinsi' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lebak', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pandeglang', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Serang', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tangerang', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Cilegon', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Serang', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tangerang', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tangerang Selatan', 'id_provinsi' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bandung', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bandung Barat', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bekasi', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bogor', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ciamis', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Cianjur', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Cirebon', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Garut', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Indramayu', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Karawang', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kuningan', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Majalengka', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pangandaran', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Purwakarta', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Subang', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sukabumi', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumedang', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tasikmalaya', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bandung', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Banjar', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bekasi', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bogor', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Cimahi', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Cirebon', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Depok', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Sukabumi', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tasikmalaya', 'id_provinsi' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Asahan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Batu Bara', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Dairi', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Deli Serdang', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Humbang Hasundutan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Karo', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Labuhan Batu', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Labuhan Batu Selatan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Labuhan Batu Utara', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Langkat', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mandailing Natal', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nias', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nias Barat', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nias Selatan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nias Utara', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Padang Lawas', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Padang Lawas Utara', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pakpak Bharat', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Samosir', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Serdang Bedagai', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Simalungun', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tapanuli Selatan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tapanuli Tengah', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tapanuli Utara', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Toba Samosir', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Binjai', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Gunungsitoli', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Medan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Padang Sidempuan', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pematang Siantar', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Sibolga', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tanjung Balai', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tebing Tinggi', 'id_provinsi' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Barat', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Barat Daya', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Besar', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Jaya', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Selatan', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Singkil', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Tamiang', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Tengah', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Tenggara', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Timur', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Aceh Utara', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bener Meriah', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bireuen', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gayo Lues', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nagan Raya', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pidie', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pidie Jaya', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Simeulue', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Banda Aceh', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Langsa', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Lhokseumawe', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Sabang', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Subulussalam', 'id_provinsi' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Agam', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Dharmasraya', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Mentawai', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lima Puluh Koto/Kota', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Padang Pariaman', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pasaman', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pasaman Barat', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pesisir Selatan', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sijunjung (Sawah Lunto Sijunjung)', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Solok', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Solok Selatan', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tanah Datar', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bukittinggi', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Padang', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Padang Panjang', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pariaman', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Payakumbuh', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Sawah Lunto', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Solok', 'id_provinsi' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bintan', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Karimun', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Anambas', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lingga', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Natuna', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Batam', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tanjung Pinang', 'id_provinsi' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bengkalis', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Indragiri Hilir', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Indragiri Hulu', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kampar', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Meranti', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kuantan Singingi', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pelalawan', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Rokan Hilir', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Rokan Hulu', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Siak', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Dumai', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pekanbaru', 'id_provinsi' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banyuasin', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Empat Lawang', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lahat', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Muara Enim', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Musi Banyuasin', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Musi Rawas', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ogan Ilir', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ogan Komering Ilir', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ogan Komering Ulu', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ogan Komering Ulu Selatan', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ogan Komering Ulu Timur', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Lubuk Linggau', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pagar Alam', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Palembang', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Prabumulih', 'id_provinsi' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bangka', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bangka Barat', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bangka Selatan', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bangka Tengah', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Belitung', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Belitung Timur', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pangkal Pinang', 'id_provinsi' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lampung Barat', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lampung Selatan', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lampung Tengah', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lampung Timur', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lampung Utara', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mesuji', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pesawaran', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pesisir Barat', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pringsewu', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tanggamus', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tulang Bawang', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tulang Bawang Barat', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Way Kanan', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bandar Lampung', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Metro', 'id_provinsi' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Batang Hari', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bungo', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kerinci', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Merangin', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Muaro Jambi', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sarolangun', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tanjung Jabung Barat', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tanjung Jabung Timur', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tebo', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Jambi', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Sungaipenuh', 'id_provinsi' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bengkulu Selatan', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bengkulu Tengah', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bengkulu Utara', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kaur', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepahiang', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lebong', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Muko Muko', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Rejang Lebong', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Seluma', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bengkulu', 'id_provinsi' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banjarnegara', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banyumas', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Batang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Blora', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Boyolali', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Brebes', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Cilacap', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Demak', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Grobogan', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jepara', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Karanganyar', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kebumen', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kendal', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Klaten', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kudus', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Magelang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pati', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pekalongan', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pemalang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Purbalingga', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Purworejo', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Rembang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Semarang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sragen', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sukoharjo', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tegal', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Temanggung', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Wonogiri', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Wonosobo', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Magelang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pekalongan', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Salatiga', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Semarang', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Surakarta (Solo)', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tegal', 'id_provinsi' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bantul', 'id_provinsi' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gunung Kidul', 'id_provinsi' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kulon Progo', 'id_provinsi' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sleman', 'id_provinsi' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Yogyakarta', 'id_provinsi' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bangkalan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banyuwangi', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Blitar', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bojonegoro', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bondowoso', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gresik', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jember', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jombang', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kediri', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lamongan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lumajang', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Madiun', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Magetan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Malang', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mojokerto', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nganjuk', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ngawi', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pacitan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pamekasan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pasuruan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ponorogo', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Probolinggo', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sampang', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sidoarjo', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Situbondo', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumenep', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Trenggalek', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tuban', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tulungagung', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Batu', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Blitar', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Kediri', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Madiun', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Malang', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Mojokerto', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pasuruan', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Probolinggo', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Surabaya', 'id_provinsi' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Balangan', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banjar', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Barito Kuala', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Hulu Sungai Selatan', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Hulu Sungai Tengah', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Hulu Sungai Utara', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kotabaru', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tabalong', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tanah Bumbu', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tanah Laut', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tapin', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Banjarbaru', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Banjarmasin', 'id_provinsi' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Barito Selatan', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Barito Timur', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Barito Utara', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gunung Mas', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kapuas', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Katingan', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kotawaringin Barat', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kotawaringin Timur', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lamandau', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Murung Raya', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pulang Pisau', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Seruyan', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sukamara', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Palangka Raya', 'id_provinsi' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Berau', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kutai Barat', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kutai Kartanegara', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kutai Timur', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Paser', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Penajam Paser Utara', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Balikpapan', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bontang', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Samarinda', 'id_provinsi' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bulungan (Bulongan)', 'id_provinsi' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Malinau', 'id_provinsi' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nunukan', 'id_provinsi' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tana Tidung', 'id_provinsi' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tarakan', 'id_provinsi' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bengkayang', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kapuas Hulu', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kayong Utara', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ketapang', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kubu Raya', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Landak', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Melawi', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pontianak', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sambas', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sanggau', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sekadau', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sintang', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Pontianak', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Singkawang', 'id_provinsi' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Badung', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bangli', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Buleleng', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gianyar', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jembrana', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Karangasem', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Klungkung', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tabanan', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Denpasar', 'id_provinsi' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bima', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Dompu', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lombok Barat', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lombok Tengah', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lombok Timur', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lombok Utara', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumbawa', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumbawa Barat', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bima', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Mataram', 'id_provinsi' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Alor', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Belu', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ende', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Flores Timur', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kupang', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lembata', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Manggarai', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Manggarai Barat', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Manggarai Timur', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nagekeo', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Ngada', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Rote Ndao', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sabu Raijua', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sikka', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumba Barat', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumba Barat Daya', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumba Tengah', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sumba Timur', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Timor Tengah Selatan', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Timor Tengah Utara', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Kupang', 'id_provinsi' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bantaeng', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Barru', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bone', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bulukumba', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Enrekang', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gowa', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jeneponto', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Luwu', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Luwu Timur', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Luwu Utara', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Maros', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pangkajene Kepulauan', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pinrang', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Selayar (Kepulauan Selayar)', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sidenreng Rappang/Rapang', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sinjai', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Soppeng', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Takalar', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tana Toraja', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Toraja Utara', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Wajo', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Makassar', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Palopo', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Parepare', 'id_provinsi' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Majene', 'id_provinsi' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mamasa', 'id_provinsi' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mamuju', 'id_provinsi' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mamuju Utara', 'id_provinsi' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Polewali Mandar', 'id_provinsi' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bombana', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Buton', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Buton Utara', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kolaka', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kolaka Utara', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Konawe', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Konawe Selatan', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Konawe Utara', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Muna', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Wakatobi', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bau-Bau', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Kendari', 'id_provinsi' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banggai', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Banggai Kepulauan', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Buol', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Donggala', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Morowali', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Parigi Moutong', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Poso', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sigi', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tojo Una-Una', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Toli-Toli', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Palu', 'id_provinsi' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bolaang Mongondow (Bolmong)', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bolaang Mongondow Selatan', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bolaang Mongondow Timur', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bolaang Mongondow Utara', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Sangihe', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Talaud', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Minahasa', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Minahasa Selatan', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Minahasa Tenggara', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Minahasa Utara', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Bitung', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Kotamobagu', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Manado', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tomohon', 'id_provinsi' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Boalemo', 'id_provinsi' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Bone Bolango', 'id_provinsi' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gorontalo', 'id_provinsi' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Gorontalo Utara', 'id_provinsi' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pohuwato', 'id_provinsi' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Gorontalo', 'id_provinsi' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Buru', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Buru Selatan', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Aru', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Maluku Barat Daya', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Maluku Tengah', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Maluku Tenggara', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Maluku Tenggara Barat', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Seram Bagian Barat', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Seram Bagian Timur', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Ambon', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tual', 'id_provinsi' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Halmahera Barat', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Halmahera Selatan', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Halmahera Tengah', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Halmahera Timur', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Halmahera Utara', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Sula', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pulau Morotai', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Ternate', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Tidore Kepulauan', 'id_provinsi' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Asmat', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Biak Numfor', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Boven Digoel', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Deiyai (Deliyai)', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Dogiyai', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Intan Jaya', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jayapura', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Jayawijaya', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Keerom', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kepulauan Yapen (Yapen Waropen)', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Lanny Jaya', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mamberamo Raya', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mamberamo Tengah', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mappi', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Merauke', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Mimika', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nabire', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Nduga', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Paniai', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pegunungan Bintang', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Puncak', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Puncak Jaya', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sarmi', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Supiori', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tolikara', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Waropen', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Yahukimo', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Yalimo', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Jayapura', 'id_provinsi' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Fakfak', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Kaimana', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Manokwari', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Manokwari Selatan', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Maybrat', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Pegunungan Arfak', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Raja Ampat', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sorong', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Sorong Selatan', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Tambrauw', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Teluk Bintuni', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kabupaten Teluk Wondama', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Kota Sorong', 'id_provinsi' => 34, 'created_at' => now(), 'updated_at' => now()],
        ];

        $chunks = array_chunk($collections, config('app.array_chunks_limit'));
        collect($chunks)->each(function ($data) {
            KabupatenKota::insert($data);
        });
    }
}
